spring.profiles.active=dev

spring.output.ansi.enabled=ALWAYS

# Database configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.error.include-exception=true

jwt.secret=aB9#mP2@nQ8!xZ5&wR7*vT1^yU6%sL4xJ3$k9#mP2@nQ8!xZ5&wR7*vT1^yU6
jwt.expiration=86400000