spring.application.name=todosimple-api

spring.output.ansi.enabled=ALWAYS

# Database configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/todosimple?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.error.include-exception=false

jwt.secret=aB9#mP2@nQ8!xZ5&wR7*vT1^yU6%sL4xJ3$k9#mP2@nQ8!xZ5&wR7*vT1^yU6
jwt.expiration=86400000